#!/bin/sh

URL=${URL:-'git://github.com/dmorilha/gitcat.git'};
BRANCH=${BRANCH:-'master'};
FILE=${FILE:-'gitcat'};

GIT_BINARY=${GIT_BINARY:-$( which git; )};
TMPDIR=${TMPDIR:-$( mktemp -d 2>/dev/null )};

cd "${TMPDIR}";
"${GIT_BINARY}" init -q;
"${GIT_BINARY}" fetch -q --depth 1 --no-recurse-submodules --no-tags "${URL}" "${BRANCH}";
"${GIT_BINARY}" cat-file -p "FETCH_HEAD:${FILE}";
rm -Rf "${TMPDIR}";
